version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak_tls
    restart: always
    ports:
      # - 8080:8080
      - 127.1.0.1:443:8443
  
    volumes:
      - C:\develop\Docker\keycloak\localdata\:/opt/jboss/keycloak/standalone/data
      - C:\develop\certificates\keycloak.codewrecks.com\cert.pem:/etc/x509/https/tls.crt
      - C:\develop\certificates\keycloak.codewrecks.com\privkey.pem:/etc/x509/https/tls.key
    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=NnyAcsQpoA5fNeHBrSZ6yCZNo3w5
