version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak_tls
    restart: always
    ports:
      # - 8080:8080
      - 127.1.0.1:443:8443
  
    volumes:
      - S:\secure\keycloak.codewrecks.com\cert.pem:/etc/x509/https/tls.crt
      - S:\secure\keycloak.codewrecks.com\privkey.pem:/etc/x509/https/tls.key
    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=my-memorable-secure-password